# Generated by Django 4.0.4 on 2022-06-03 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_postcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcomment',
            options={'ordering': ('-created',)},
        ),
    ]
